### ISSUE TITLE
Temporary keychains are locked after 5 minutes

### ISSUE THREAD

**Issue by benjamindetroch** [richardszalay/spare-keys#6]
Temporary keychains get locked after 5 minutes. That's the default timeout for newly created keychains on OS X. We run into trouble with long running build processes that require access to the keychain after the timeout has expired.
I suggest to not have a timeout on these temporary keychains. They get deleted after the code block completes anyway.

I've sent a pull request, #5, to remove the timeout and leave the keychain unlocked. 

Cheers,
Ben

**Comment by richardszalay** [comment]
Fantastic, thanks for catching this. I'll get it merged as soon as I can.

**Comment by bitcrumb** [comment]
👍

**Comment by richardszalay** [comment]
This PR has been merged and included in the 1.2.0 release
